import { Club } from "./types";

export const CLUBS: Club[] = [
  { kuerzel: "ALT", name: "Altonaer Schachklub v. 1873 e. V." },
  { kuerzel: "BAR", name: "Stadtpark Barrio 1996 e. V." },
  { kuerzel: "BBK", name: "Barmbeker Schachklub von 1926 e. V." },
  { kuerzel: "BGD", name: "Bergedorfer Schachverein von 1909 e. V." },
  { kuerzel: "BIL", name: "Spvg. Billstedt-Horn v. 1891 e. V., Schachabteilung" },
  { kuerzel: "BLA", name: "Schachvereinigung Blankenese von 1923 e. V." },
  { kuerzel: "BSC", name: "Bille Schach-Club von 1924 e. V." },
  { kuerzel: "BSG", name: "TSG Bergedorf von 1860 e. V." },
  { kuerzel: "BSK", name: "Bramfelder Schachklub von 1947 e. V." },
  { kuerzel: "BST", name: "Bergstedter Schachklub von 1962" },
  { kuerzel: "CON", name: "Wandsbeker TSV Concordia e. V." },
  { kuerzel: "DIA", name: "Schachverein Diagonale Harburg e. V." },
  { kuerzel: "DIO", name: "Schachclub Diogenes von 1977 e. V." },
  { kuerzel: "FAR", name: "Schach-Club Farmsen e. V." },
  { kuerzel: "FBK", name: "Schachgrp. Süderelbe im TV Fischbek v. 1921 e. V." },
  { kuerzel: "GEH", name: "Hamburger Gehörlosen Sportverein v. 1904 e. V." },
  { kuerzel: "GHD", name: "SV Großhansdorf, Schachabteilung" },
  { kuerzel: "HBG", name: "Schachclub Schwarz-Weiß Harburg e. V." },
  { kuerzel: "HSK", name: "Hamburger Schachklub von 1830 e. V." },
  { kuerzel: "KSP", name: "Schachclub Königsspringer Hamburg v. 1984 e. V." },
  { kuerzel: "LGH", name: "Langenhorner Schachfreunde von 1928 e. V." },
  { kuerzel: "LUP", name: "Sportverein Lurup v. 1923 e. V., Schachabteilung" },
  { kuerzel: "MAT", name: "Schachklub Marmstorf im SV Grün-Weiß Harburg e. V." },
  { kuerzel: "MUE", name: "Mümmelmannsberger SV v. 1974 e. V., Schachabteilung" },
  { kuerzel: "NIE", name: "Niendorfer TSV v. 1919 e. V., Schachabteilung" },
  { kuerzel: "PIN", name: "Pinneberger Schachclub von 1932 e. V." },
  { kuerzel: "ROE", name: "SC Rösselsprung e. V." },
  { kuerzel: "SAS", name: "Schachfreunde Sasel von 1947 e. V." },
  { kuerzel: "SFR", name: "Schachfreunde Hamburg von 1934 e. V." },
  { kuerzel: "SKJ", name: "Schachklub Johanneum Eppendorf e. V." },
  { kuerzel: "SSH", name: "Schachclub Schachelschweine e. V." },
  { kuerzel: "STE", name: "SC Sternschanze v. 1911 e. V." },
  { kuerzel: "STP", name: "FC St. Pauli von 1910 e. V., Schachabteilung" },
  { kuerzel: "SVE", name: "SV Eidelstedt von 1880 e. V." },
  { kuerzel: "UNE", name: "Schachklub Union Eimsbüttel von 1871 e. V." },
  { kuerzel: "VDF", name: "Volksdorfer Schachklub von 1948 e. V." },
  { kuerzel: "WDF", name: "Walddörfer SV v. 1924 e. V." },
  { kuerzel: "WED", name: "Schachfreunde Wedel e. V." },
  { kuerzel: "WEI", name: "Schachklub Weisse Dame Hamburg" },
  { kuerzel: "WIC", name: "SGM Wichernschule" },
].sort((a, b) => a.name.localeCompare(b.name, "de"));

export const DEFAULT_CLUB_KUERZEL = "STP";
